export CONFIG=$HOME/.config
export CONFIG_NIXOS=$CONFIG/nixos-config
export CONFIG_NVIM=$CONFIG/nvim
export CONFIG_DOTFILES=$CONFIG/dotfiles
export CONFIG_ZSH=$CONFIG_DOTFILES/zsh
export CONFIG_I3=$CONFIG_DOTFILES/i3
export CONFIG_I3STATUS=$CONFIG_DOTFILES/i3status
